[package]
name = "ecli"
version = "0.1.0"
authors = ["Phil Proctor <philliptproctor@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
