trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

strategy:
  matrix:
    stable:
      rustup_toolchain: stable

pool:
  vmImage: "ubuntu-16.04"

container: rust:1.36-buster

steps:
  - script: |
      rustup target add x86_64-unknown-linux-musl
      cargo build --release --target x86_64-unknown-linux-musl
      strip target/x86_64-unknown-linux-musl/release/ecli
      gzip -9 -kf target/x86_64-unknown-linux-musl/release/ecli
    displayName: 'Build package'

  - task: GitHubRelease@0
    displayName: 'Create GitHub Release'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    inputs:
      gitHubConnection: proctorlabsToken
      repositoryName: proctorlabs/ecli           
      assets: $(Build.ArtifactStagingDirectory)/target/x86_64-unknown-linux-musl/release/ecli.gz
