resources:
  containers:
    - container: rust-builder
      image: rust:1.36-buster

trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

jobs:
  - job: build

    pool:
      vmImage: "ubuntu-16.04"
    container: rust-builder

    steps:
      - script: "GITHUB_TOKEN=$(variables['is_tag']) ./.ci/build.sh -bag"
        displayName: "Build package"
