resources:
  containers:
    - container: rust-builder
      image: rust:1.36-buster

trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

variables:
  RELEASE_TAG: "$(Build.SourceBranchName)"
  IS_TAG: "${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}"

jobs:
  - job: build

    pool:
      vmImage: "ubuntu-16.04"
    container: rust-builder

    steps:
      - script: "./.ci/build.sh -ba"
        displayName: "Build package"
      - script: "./.ci/build.sh -g"
        displayName: "Push release to github"
        condition: eq( variables['IS_TAG'], 'True' )
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
